name: "Terraform-Plan-Infra-Plan"

on:
  push:
    branches:
      - Developer
  
jobs:
  terraform:
    name: "Terraform"
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID:
      AWS_SECRET_ACCESS_KEY:
      AWS_REGION: 'us-east-1'

    steps:
      - name:
        uses:

      - name:
        uses:

      - name:
        uses:
      
      - name:
        uses: